apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: core-netshow
  name: core-netshow
  namespace: default 
spec:
  replicas: 10
  selector:
    matchLabels:
      app: core-netshow
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: core-netshow
    spec:
      containers:
      - image: akibirio/core-helloworld:v1.0.0
        imagePullPolicy: IfNotPresent
        name: core-netshow
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
